name: Run Unix Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install coverage
      - name: Run Tests
        run: |
          coverage run --source=. --omit=extended_train_test_split/__init__.py,setup.py,test/* -m unittest discover -v
      - name: Show Coverage
        run: |
          coverage report -m > temp.txt
          cat temp.txt
          python .github/workflows/coverage_helper.py
          echo "COVERAGE_PERCENT=$(cat temp2.txt)" >> $GITHUB_ENV

      - name: Comment Low Coverage
        if: ${{ env.COVERAGE_PERCENT < 0.90 }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Test Coverage is below 90%, please increase this before merging.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
