name: Run Tests
on:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} Subtest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          auto-update-conda: true
          channels: defaults,conda-forge
          channel-priority: flexible
          extra-specs: |
            python=${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install -e .[molecules]
          python -m pip install coverage
      - name: Run Tests
        run: |
          coverage run --source=. --omit=astartes/__init__.py,setup.py,test/* -m unittest discover -v
      - name: Show Coverage
        run: |
          coverage report -m
