name: Update JORS Branch
on:
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: git nonsense
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: jors-paper
          github_token: ${{ github.token }}